<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="dmhuy" name="restDemo.RestAPI" tests="1" failures="0" timestamp="11 May 2017 04:21:48 GMT" time="0.023" errors="1">
  <testcase name="API" time="0.023" classname="restDemo.RestAPI">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at org.testng.internal.ArrayIterator.hasNext(MethodHelper.java:350)
	at org.testng.internal.Parameters$2.hasNext(Parameters.java:448)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1117)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- API -->
</testsuite> <!-- restDemo.RestAPI -->
